Добавляет главную страницу и страницу каталога
htmlacademy-htmlcss/2288929-sedona-1 pull request #2
Opened 2024-01-18 09:00 UTC by olissotib

2024-01-18 09:11 UTC, summertime-fms requested changes

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +        </p>
лучше завернуть в ссылку, просто без атрибута href
ссылка - инлайновый тег, а параграф потащит за собой отступы и другие ненужные стили.

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +            <a class="navigation-link navigation-link-current" href="#">Главная</a>
для красоты можно еще ссылкам добавлять атрибут title
это особенно приветствуется на ссылках внутри которых нет текста, а допустим только иконка.

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +    <main class="page-main">
префикс page- у шапки с подвалом и у этого тега по сути ничего не сообщает нам) я за простоту)
header всегда один на сайте, то есть не будет такого что есть page-header а есть какой нибудь non-page-header :В

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +        <h2 class="lead-title">Приезжайте в Седону отдохнуть в комфорте и уюте!</h2>
достаточно будет того, который визуально отображается.  верхний заголовок избыточный

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +        <h2 class="lead-title">Заинтересовались?</h2>
аналогично выше

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +          <input class="subscription-filed" type="email" name="email-subscription" placeholder="Ваш e-mail" required>
в name достаточно email просто указать
так будет чуть чуть проще людям которые будут писать бек)

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +          <img src="#" alt="Вконтакте">
отступ вложенности

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +      <a href="+78128121212" class="footer-phone">+7 (812) 812-12-12</a>
протокол tel: забыд

2024-01-18 09:11 UTC, summertime-fms commented on index.html
> +      <p class="footer-logo">
ссылка должна быть которая ведет на сайт академии по ТЗ

2024-01-18 09:11 UTC, summertime-fms commented on catalog.html
> +            <form action="https://echo.htmlacademy.ru/" class="filters-form" method="get">
такие формы постом обычно отправляются

2024-01-18 09:11 UTC, summertime-fms commented on catalog.html
> +              <a class="catalog-view-button catalog-view-button-current" href="#">
это будут кнопки)

2024-01-18 09:11 UTC, summertime-fms commented on catalog.html
> +        <section class="catalog-hotels">
h2 для секции потерял

2024-01-18 09:11 UTC, summertime-fms commented on catalog.html
> +                    </li>
очень громоздко, надо переделать. в тг объясню как

2024-01-18 12:28 UTC, olissotib commented on index.html
> +        </p>
Выбрал параграф, т.к думал сделать некий контейнер для изображения, для контроля вертикальных размеров и отступов. Этот приём был показан в МК [«Вёрстка компонентов интерфейса по макету»](https://up.htmlacademy.ru/profession/frontender-individual/1/fe-start/1/module/9). Тут применил по шаблону

2024-01-18 12:40 UTC, olissotib commented on index.html
> +    <main class="page-main">
А как же случаи когда внутри какого-нибудь section появляется свой header и footer? И тут смысл был в том, чтобы указать что это шапка именно главной страницы, а не catalog или какой-то еще.

2024-01-18 12:42 UTC, olissotib commented on index.html
> +            <a class="navigation-link navigation-link-current" href="#">Главная</a>
А верно ли что title почти всегда может дублировать alt в тегах img?

2024-01-18 12:48 UTC, olissotib commented on index.html
> +          <input class="subscription-filed" type="email" name="email-subscription" placeholder="Ваш e-mail" required>
Смутило что дублируется текст в type и name. Чисто визуально как-то резануло

2024-01-18 13:02 UTC, olissotib commented on index.html
> +        <h2 class="lead-title">Заинтересовались?</h2>
Мне почему-то жутко не понравился заголовок-призыв, типа "Заинтересовались?". Хотя далее параграф объясняет о чем речь, но, показалось, что нужно прям конкретно указать о чем этот блок.

2024-01-19 08:17 UTC, summertime-fms commented on index.html
> +            <a class="navigation-link navigation-link-current" href="#">Главная</a>
тайтл это больше про интерактивные элементы, а img таковым не является.

2024-01-19 08:17 UTC, summertime-fms commented on index.html
> +    <main class="page-main">
окей, принимается

2024-01-19 08:20 UTC, summertime-fms commented on index.html
> +        <h2 class="lead-title">Заинтересовались?</h2>
Ну представь вот через скринридер человек идет по сайту и ему сообщают заголовок первый и он как бы ожидает что дальше пойдет контент по этому заголовку. но идет второй заголовок. и тут 2 вопроса - зачем два заголовка на один раздел и если нет контента после первого заголовка то может это сбой, что то не дозагрузилось на страницу и тд. 

в общем когда есть в макете заголовок, нравится он или нет, лучше вставлять его и не писать свои.

2024-01-19 08:21 UTC, summertime-fms commented on index.html
> +          <input class="subscription-filed" type="email" name="email-subscription" placeholder="Ваш e-mail" required>
name - это сугубо  для бекенда. на фронте этот атрибут ничего не делает. а вот type делает. поэтому тут надо больше на функциональность смотреть, а то что визуально режет, с этим ничего не поделаешь.

2024-01-19 09:49 UTC, olissotib commented on index.html
> +        <h2 class="lead-title">Заинтересовались?</h2>
Понял насчет двух заголовков

2024-01-19 09:50 UTC, olissotib commented on index.html
> +          <input class="subscription-filed" type="email" name="email-subscription" placeholder="Ваш e-mail" required>
> то что визуально режет, с этим ничего не поделаешь.
да, конечно. Дело привычки

2024-01-19 17:58 UTC, merged